/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Task2;

import java.awt.Color;

/**
 *
 * @author Dulapah Vibulsanti
 */
public class pftCalculator extends javax.swing.JFrame {

    private int score = 0;
    private int pullups = 0;
    private int situps = 0;
    private int runMin = 0;
    private int runSec = 0;

    /**
     * Creates new form pftCalculator
     */
    public pftCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButtonGroups = new javax.swing.ButtonGroup();
        Icon = new javax.swing.JLabel();
        pullupsLabel = new javax.swing.JLabel();
        situpsLabel = new javax.swing.JLabel();
        runLabel = new javax.swing.JLabel();
        pftScoreLabel = new javax.swing.JLabel();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        runMinField = new javax.swing.JTextField();
        runSecField = new javax.swing.JTextField();
        pullupsField = new javax.swing.JTextField();
        situpsField = new javax.swing.JTextField();
        pftScoreField = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        closeMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        indexMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PFT Calculator");
        setBounds(new java.awt.Rectangle(0, 0, 400, 400));
        setResizable(false);

        Icon.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dulapah Vibulsanti\\Downloads\\arona_channel.png")); // NOI18N

        pullupsLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pullupsLabel.setText("Pullups/Flex Arm");

        situpsLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        situpsLabel.setText("Situps");

        runLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        runLabel.setText("Run (min /sec)");

        pftScoreLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pftScoreLabel.setText("PFT Score");

        radioButtonGroups.add(maleRadioButton);
        maleRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maleRadioButton.setSelected(true);
        maleRadioButton.setText("Male");
        maleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRadioButtonActionPerformed(evt);
            }
        });

        radioButtonGroups.add(femaleRadioButton);
        femaleRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        femaleRadioButton.setText("Female");

        runMinField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runMinFieldActionPerformed(evt);
            }
        });

        pullupsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pullupsFieldActionPerformed(evt);
            }
        });

        situpsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                situpsFieldActionPerformed(evt);
            }
        });

        pftScoreField.setEditable(false);
        pftScoreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pftScoreFieldActionPerformed(evt);
            }
        });

        calculateButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        fileMenu.setText("File");

        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        closeMenuItem.setText("Close");
        closeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(closeMenuItem);

        jMenuBar1.add(fileMenu);

        editMenu.setText("Edit");

        cutMenuItem.setText("Cut");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(cutMenuItem);

        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        jMenuBar1.add(editMenu);

        helpMenu.setText("Help");

        indexMenuItem.setText("Index");
        helpMenu.add(indexMenuItem);

        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pullupsLabel)
                    .addComponent(situpsLabel)
                    .addComponent(runLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pullupsField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(situpsField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(pftScoreLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(pftScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(runMinField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(runSecField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maleRadioButton)
                                    .addComponent(femaleRadioButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(Icon)
                                .addGap(29, 29, 29))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(calculateButton)
                        .addGap(170, 170, 170))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(maleRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(femaleRadioButton))
                    .addComponent(Icon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(pullupsLabel)
                    .addComponent(pullupsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(situpsLabel)
                    .addComponent(situpsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(runLabel)
                    .addComponent(runMinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(runSecField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(pftScoreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pftScoreLabel))
                .addGap(18, 18, 18)
                .addComponent(calculateButton)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeMenuItemActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void maleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRadioButtonActionPerformed

    private void pullupsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pullupsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pullupsFieldActionPerformed

    private void runMinFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runMinFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_runMinFieldActionPerformed

    private void situpsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_situpsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_situpsFieldActionPerformed

    private void pftScoreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pftScoreFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pftScoreFieldActionPerformed

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        if (!pullupsField.getText().isEmpty()) {
            pullups = Integer.parseInt(pullupsField.getText());
        }
        if (!situpsField.getText().isEmpty()) {
            situps = Integer.parseInt(situpsField.getText());
        }
        if (!runMinField.getText().isEmpty()) {
            runMin = Integer.parseInt(runMinField.getText());
        }
        if (!runSecField.getText().isEmpty()) {
            runSec = Integer.parseInt(runSecField.getText());
        }
        score += Math.min(100, situps);
        if (maleRadioButton.isSelected()) {
            score += Math.min(20, pullups) * 5;
            if ((runMin * 60) + runSec < 28 * 60) {
                score += 100;
                if ((runMin * 60) + runSec > 18 * 60) {
                    score -= ((((runMin - 18) * 60) + runSec) / 10);
                }
            } else {
                runMinField.setBackground(Color.RED);
                runSecField.setBackground(Color.RED);
                runMinField.setForeground(Color.WHITE);
                runSecField.setForeground(Color.WHITE);
            }
        } else {
            score += Math.min(40, pullups) + (Math.max(0, pullups - 40) * 2);
            if ((runMin * 60) + runSec < 31 * 60) {
                score += 100;
                if ((runMin * 60) + runSec > 21 * 60) {
                    score -= ((((runMin - 21) * 60) + runSec) / 10);
                }
            } else {
                runMinField.setBackground(Color.RED);
                runSecField.setBackground(Color.RED);
                runMinField.setForeground(Color.WHITE);
                runSecField.setForeground(Color.WHITE);
            }
        }
        pftScoreField.setForeground(Color.WHITE);
        if (score < 135) {
            pftScoreField.setBackground(Color.RED);
            pftScoreField.setText("Fail");
        } else {
            pftScoreField.setBackground(Color.GREEN);
            pftScoreField.setText(String.valueOf(score));
        }
    }//GEN-LAST:event_calculateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pftCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pftCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pftCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pftCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pftCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Icon;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JButton calculateButton;
    private javax.swing.JMenuItem closeMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem indexMenuItem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JTextField pftScoreField;
    private javax.swing.JLabel pftScoreLabel;
    private javax.swing.JTextField pullupsField;
    private javax.swing.JLabel pullupsLabel;
    private javax.swing.ButtonGroup radioButtonGroups;
    private javax.swing.JLabel runLabel;
    private javax.swing.JTextField runMinField;
    private javax.swing.JTextField runSecField;
    private javax.swing.JTextField situpsField;
    private javax.swing.JLabel situpsLabel;
    // End of variables declaration//GEN-END:variables
}
